# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'BreakOut' do


pod 'Instabug', '~> 5.1.0'
pod 'Fabric', '~> 1.6.6'
pod 'Crashlytics', '~> 3.5.0'

# Flurry -> App Analytics (Funnel, ...)
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.4'
pod 'Flurry-iOS-SDK/FlurrySDK', '~> 7.5.0'

# Database
pod 'MagicalRecord', '~> 2.3.2'
pod 'Pantry', '~> 0.2.1'

# Networking
pod 'AFNetworking', '~> 2.6.3'
pod 'AFOAuth2Manager', git: 'https://github.com/AFNetworking/AFOAuth2Manager'

# UI
pod 'SpinKit', '~>1.2.0'
pod 'MBProgressHUD'
pod 'SlideMenuControllerSwift'
pod 'LECropPictureViewController', '~> 0.1.2'
pod 'SwiftDate', '~> 3.0.1'

use_frameworks!

pod 'JLToast', '~> 1.3'

pod 'netfox'. '~> 1.7.2'

pod 'ReachabilitySwift', git: 'https://github.com/ashleymills/Reachability.swift'

# Image Caching
pod 'SDWebImage', '~>3.7'

end

target 'BreakOutTests' do

end

