# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'BreakOut' do

pod 'Instabug'
pod 'Fabric'
pod 'Crashlytics'
pod 'MagicalRecord'
pod 'AFNetworking'

use_frameworks!

pod 'netfox'

pod 'ReachabilitySwift', git: 'https://github.com/ashleymills/Reachability.swift'

# Image Caching
pod 'SDWebImage', '~>3.7'

end

target 'BreakOutTests' do

end

