language: objective-c

before_install: gem install cocoapods -v '= 1.0.1' && pod repo update

xcode_project: BreakOut.xcodeproj
xcode_scheme: BreakOutTests
osx_image: xcode8
xcode_sdk: iphonesimulator10.0

script:
- xcodebuild clean build test -workspace BreakOut.xcworkspace -scheme BreakOutTests
