language: objective-c
cache: cocoapods
osx_image: xcode8

xcode_project: BreakOut.xcodeproj
xcode_scheme: BreakOutTests
osx_image: xcode8
xcode_sdk: iphonesimulator10.0

sudo: required

notifications:
  slack:
    rooms:
      - breakoutevent:kV9edN91PBbtZA3sjA2ChnuP
    on_success: change
    on_failure: change

before_install:
  - pod repo update > /dev/null
  - openssl aes-256-cbc -K $encrypted_7cb16b9c01f6_key -iv $encrypted_7cb16b9c01f6_iv -in PrivateConstants.swift.enc -out BreakOut/PrivateConstants.swift -d

script:
  - xcodebuild test -workspace BreakOut.xcworkspace -scheme BreakOutTests -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.1' CODE_SIGNING_REQUIRED=NO
