language: objective-c

xcode_project: BreakOut.xcodeproj
xcode_scheme: BreakOutTests
osx_image: xcode8.0
xcode_sdk: iphonesimulator10.0

script:
- xcodebuild clean build test -workspace BreakOut.xcworkspace -scheme BreakOutTests
