language: objective-c
cache: cocoapods
osx_image: xcode8

sudo: required

dependencies:
  pre:
    - gem update --system

before_install:
  - sudo gem update fastlane --no-ri --no-rdoc --no-document
  - pod repo update
  - openssl aes-256-cbc -K $encrypted_7cb16b9c01f6_key -iv $encrypted_7cb16b9c01f6_iv -in PrivateConstants.swift.enc -out BreakOut/PrivateConstants.swift -d


script:
  - fastlane test
